### ISSUE TITLE
Expose more APIs for the a Geth nodes

### ISSUE THREAD

**Issue by olawiberg** [the-chaingang/ethereal#25]
Currently, we don't expose the `admin` api for the nodes. This API is very helpful when developing and testing the node configurations.  We are also missing the `miner` api for the miner node, without that we can start/stop the miner.

**Comment by zomglings** [comment]
@olawiberg : This didn't require us to change any code - simply pass `--rpcapi` arguments to node in the `ethereal` manifest.

Here is a PR with a test which shows how to do this: https://github.com/the-chaingang/ethereal/pull/26
